### ISSUE TITLE
ons-splitter-side content overlaps ios statusbar when scrolling

### ISSUE THREAD

**Issue by rockneverdies55** [OnsenUI/OnsenUI#1315]
Using onsen-2.  
I have no issues at the initial state before scrolling. When scrolled, the content within `ons-splitter-side` overlaps the ios statusbar.

**Comment by IliaSky** [comment]
Thanks for reporting. I will look into it on Monday. Until recently the splitter side wasn't even scrollable, so I guess we haven't tested this scenario.

**Comment by IliaSky** [comment]
The fix will probably be available as soon as beta.9 comes out. Until then feel free to patch it for your app with the following css: 
```css
.page__status-bar-fill + .page__background + .page__content {
  padding-top: 0px;
  top: 20px;
}
```
