### ISSUE TITLE
Toolbar Cover-Content not covering content

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#2178]
@frandiox @argelius 

I am using the newest version of Onsen and I encountered an issue:
I want to have the transparent toolbar covering the content. I added 
`modifier="transparent cover-content"` as pointed out inside the docs. It will be transparent, but not overlapping/covering the content, due to this css rule:

```css
.toolbar + .page__background + .page__content {
    margin-top: -1px;
    top: 44px;
}
```

IMHO there should be a special case css like 
`.toolbar--cover-content.toolbar + page...` with a top 0px value, am I right?

**Comment by frandiox** [comment]
@Hirbod Are you perhaps using an old CSS version? I believe that rule was removed. The `cover-content` should just add `padding-top` instead.

**Comment by Hirbod** [comment]
@frandiox prob. an old CSS, maybe.. I will need to update I guess.

**Comment by frandiox** [comment]
@Hirbod I guess you have a custom `onsen-css-components.css`. Try updating only `onsenui.css` file, this changes should be there.

**Comment by Hirbod** [comment]
Hi, just updated and it worked like you said. Anyway, I'd expect another behaviour.

This happens:
<img width="718" alt="bildschirmfoto 2017-09-11 um 03 13 40" src="https://user-images.githubusercontent.com/504909/30254971-87b5dc76-969f-11e7-9a87-3c15b1591970.png">

This is what I'd expect
<img width="713" alt="bildschirmfoto 2017-09-11 um 03 14 08" src="https://user-images.githubusercontent.com/504909/30254972-87b67f32-969f-11e7-9540-f317dc12e3d7.png">

I set a custom rule with padding-top: 0; now

**Comment by frandiox** [comment]
@Hirbod Is that background image in `.page__content`? It should be in `.page__background` instead. The latter doesn't have any padding.

**Comment by Hirbod** [comment]
I added a modifier to ons-page

```css
.page--storychat__background {
    background: url(../../assets/img/stickies/2.jpg);
    background-size: cover;
}
```

**Comment by frandiox** [comment]
@Hirbod I just tried that and it works well :confused: 
Can you check which rule is setting that padding? In the latest version only `.page__content` should have `padding-top: 44px`...

**Comment by Hirbod** [comment]
```css
.toolbar.toolbar--cover-content + .page__background + .page__content {
    padding-top: 44px;
}
```

I changed it to
```
.toolbar.toolbar--cover-content + .page__background + .page__content {
    padding-top: 0;
}
```

and then it looks like I want it to look
