### ISSUE TITLE
iPhone X Support

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#2196]
Hi,

onsen need some iPhone X Support.
iPhone X provides some new CSS Stuff:

```css
body {
    padding-top: constant(safe-area-inset-top);
    padding-top: constant(safe-area-inset-bottom);
}
```

I had to "patch" several areas of my content with this new "constant" stuff to provide fixes for the toolbar, bottom-bar and other custom elements.

https://stackoverflow.com/questions/46232812/cordova-app-not-displaying-correctly-on-iphone-x-simulator
