### ISSUE TITLE
broken design on cordova ios

### ISSUE THREAD

**Issue by irxground** [OnsenUI/OnsenUI#224]
Here is a screen shot.

![ios simulator screen shot 2014 09 22 13 14 47](https://cloud.githubusercontent.com/assets/438900/4351597/72e99fa4-420f-11e4-9c4e-51d925e795d9.png)

I fixed `www/lib/onsen/css/onsenui.css`

from:

``` css
.page__status-bar-fill + ons-toolbar {
  height: 64px;
}
.page__status-bar-fill + ons-toolbar > .center,
.page__status-bar-fill + ons-toolbar > .left,
.page__status-bar-fill + ons-toolbar > .right {
  padding-top: 20px;
}
```

to:

``` css
.page__status-bar-fill + ons-toolbar {
  height: 64px;
  padding-top: 20px;
}
```

This change works well.

---

But I don't know where to fix:
- `app/lib/onsen/css/onsenui.css` ?
- `build/css/onsenui.css` ?
- or else

Please apply this change.
