### ISSUE TITLE
css-components: Some modifier classes mix in their block

### ISSUE THREAD

**Issue by emccorson** [OnsenUI/OnsenUI#2938]
There are some places in the CSS Components where a modifier class mixes in its block.

For example:
```css
/* css-components/src/components/button.css */

.button {
  @mixin button;               /* <--- this is correct */
}

.button--large--cta {
  @mixin button;                  /* <----- this is not correct */
  border: none;
  background-color: var(--button-cta-background-color);
  color: var(--button-cta-color);
  font-size: var(--font-size);
  font-weight: var(--font-weight--large);
  line-height: var(--button-large-line-height);
  padding: var(--button-large-padding);
  width: 100%;
  text-align: center;
  display: block;
}
```

This allows us to create a large CTA button with `<button class="button--large--cta"></button>`, but this is actually not recommended by BEM. Instead we should insist that the user has to *also* add the block class: `<button class="button button--large--cta"></button>`.

The explanation for this is in the [BEM FAQ](http://getbem.com/faq/#block-modifier-mix).

We should remove all instances where the block class is mixed in to the modifier class. This will be a breaking change so update the docs accordingly. Once nice thing is that this will help us remove our reliance on mixins.

(Also, I'm actually not sure about having two modifiers in the same class name i.e. `--large--cta`. I thought this should imply one modifier `cta` which is a subclass of `large`. An example from the BEM docs is `block--size--big`, where `big` is the modifier which is a subclass of `size`.)
