### ISSUE TITLE
Small 1px bug in nav-bar

### ISSUE THREAD

**Issue by hirbod** [OnsenUI/OnsenUI#326]
Hi,

found this:

```
..navigation-bar {
   ...
   ...
   background-size: 100% 1px;
}
```

Here:

``` css
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
  .navigation-bar {
    border-bottom: none;
    -webkit-background-size: 100% 1px; // <-- this should be 0px
    background-size: 100% 1px; // <-- this should be 0px
    background-repeat: no-repeat;
    background-position: bottom;
    background-image: -webkit-linear-gradient(90deg, #ddd, #ddd 50%, transparent 50%);
    background-image: -moz-linear-gradient(90deg, #ddd, #ddd 50%, transparent 50%);
    background-image: -o-linear-gradient(90deg, #ddd, #ddd 50%, transparent 50%);
    background-image: linear-gradient(0deg, #ddd, #ddd 50%, transparent 50%);
  }
}
```

In your component.css. This causes a small 1px border at the bottom. If I set to 0px everything looks great. I guess this is a bug? Or do you have any other reason to set this to 1px?

![img_0011](https://cloud.githubusercontent.com/assets/504909/5117371/c8d86ed2-7053-11e4-9aa5-f168c858360d.PNG)
