### ISSUE TITLE
.row + .row css

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#446]
Hi @argelius,

is there any reason, why onsenui.css has

```css
.row + .row {
   margin-top: -5px
}
```

This cause, that two ```ons-row``` elements coming after eachother will overlay themselfes. This is quite a bug imho. I've changed it now and the overlay problem is gone.
