### ISSUE TITLE
dev version cause ons-row align center to be left positioned

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#448]
Hi @argelius ,

as I told you before, the new dev version cause every ```<ons-row align="center">``` I've set to be left positioned. I've updated **only** onsenui.js and onsenui.css (not the stylus and of course no new theme as the generator on your page is not updated.

But still, I guess the problem is something else.

```CSS
.row-center {
   -webkit-box-align: center;
   -ms-flex-align: center;
   -webkit-align-items: center;
   -moz-align-items: center;
   -moz-box-align: center;
   align-items: center;
   text-align: inherit;
}
```
This is your new CSS. If I remove ```text-align: inherit;```, everything is fine! I've checked the old release (1.2.1) and text-align: inherit is new, so you did change something in the CSS. For now, I'm going to remove this attribute in my CSS, but I don't know why you guys added this, but this cause a lot of problems
