### ISSUE TITLE
Navigator animation overlays sliding menu

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#552]
From @danjarvis

So I noticed the second issue a few weeks ago after upgrading to Onsen v1.2.2

I commented on [this commit](https://github.com/OnsenUI/OnsenUI/commit/4161934bb7ebca5e80dfae14a1652efc734926ac#commitcomment-10323911) to get more details, because the CSS change is what causes the overlap when using ons-navigator with split-view.

As mentioned in the comment, you can work around this by using the following CSS:

```css
.onsen-split-view__main {
    overflow: hidden !important;
}
```

Forked example [here](http://codepen.io/danjarvis/pen/wBOYYy).
