### ISSUE TITLE
ons-list-item is set ng-disabled="true" but click event still works

### ISSUE THREAD

**Issue by zhuangperola** [OnsenUI/OnsenUI#723]
I have set attr of ons-list-item with ng-disabled, but ng-click still works.

**Comment by argelius** [comment]
Hi @zhuangperola !

Please try adding the following rule:

```css
ons-list-item[disabled] {
  pointer-events: none;
}
```
